require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'db/schema.rb'


Performance:
  Exclude:
    - 'spec/**/*'

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'Guardfile'

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - 'bin/*'
