# https://docs.docker.com/compose/rails/
---
version: '3'

services:

  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  web:
    build: .
    command: bash -c "bundle exec rake db:migrate && bundle exec rake db:seed && rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/help_me
    ports:
      - "4000:3000"
    depends_on:
      - db

  guard:
    build: .
    volumes:
      - .:/help_me
    command: bundle exec guard --no-bundler-warning --no-interactions
