# https://docs.docker.com/compose/rails/
---
version: '3'

services:
  postgres:
    image: postgres
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data

  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./tmp/redis:/data

  web:
    build: .
    command: bash -c "bundle exec rake db:migrate && bundle exec rake db:seed && rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/help_me
    ports:
      - "4000:3000"
    environment:
      - MICROSOFT_TRANSLATOR_API_KEY=${MICROSOFT_TRANSLATOR_API_KEY}
      - DATABASE_URL=postgresql://postgres@postgres:5432/help_me_development
      - REDIS_URL=redis://redis:6379/1
    depends_on:
      - postgres
      - redis

  guard:
    build: .
    volumes:
      - .:/help_me
    command: bundle exec guard --no-bundler-warning --no-interactions
